package:
  name: 'pymica'
  version: "0.1.0"

source: 
  git_branch: 47-update-conda_build
  git_url: https://github.com/meteocat/pymica.git
  

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - scikit-learn
    - gdal
    - pyproj
    - pyshp
    - shapely
  run:
    - python
    - cython
    - numpy
    - scipy
    - scikit-learn
    - gdal
    - pyproj
    - pyshp
    - shapely

about:
  home: https://github.com/meteocat/pymica
  license: MIT
  license_family: MIT
  summary: (py)Meteorological variable Interpolation based on Clustered Analysis